version: '3'

services:
  web:
    image: nginx
    restart: always
    volumes:
     - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf
     - ${NGINX_SITE_CONF_FILE}:/etc/nginx/site-abailable
     - ${LOCAL_SITES_PATH}:${REMOTE_SITES_PATH}
    ports:
     - "${WEB_LOCAL_PORT}:80"
    working_dir: ${REMOTE_SITES_PATH}
  php:
    build: ./php
    restart: always
    environment:
     - COMPOSER_HOME=${COMPOSER_HOME}
     - COMPOSER_CACHE_DIR=${COMPOSER_CACHE_DIR}
    volumes: 
     - ${LOCAL_SITES_PATH}:${REMOTE_SITES_PATH}
     - ${COMPOSER_HOME}:${COMPOSER_HOME}
     - ${COMPOSER_CACHE_DIR}:${COMPOSER_CACHE_DIR}
    working_dir: ${REMOTE_SITES_PATH}
    command: "php-fpm"
  db:
    image: mariadb
    restart: always
    ports:
     - "${DB_LOCAL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_INIT_PATH}:/docker-entrypoint-initdb.d
      - ${MYSQL_LOCAL_PATH}:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8mb4_unicode_ci']
  adminer:
    image: adminer
    ports:
     - "${ADMINER_LOCAL_PORT}:8080"
  redis:
    image: redis
    restart: always
    ports:
     - "${REDIS_LOCAL_PORT}:6379"