version: '3'

services:
  web:
    image: nginx
    restart: always
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
     - ./nginx/common:/etc/nginx/common
     - ./nginx/site-available:/etc/nginx/site-enable
     - ${LOCAL_SITES_PATH}:${REMOTE_SITES_PATH}
    ports:
     - "${WEB_LOCAL_PORT}:80"
    working_dir: ${REMOTE_SITES_PATH}
  php:
    build: ./php
    restart: always
    environment:
     - COMPOSER_HOME=$HOME/${COMPOSER_HOME}
     - COMPOSER_CACHE_DIR=$HOME/${COMPOSER_CACHE_DIR}
    volumes: 
     - ${LOCAL_SITES_PATH}:${REMOTE_SITES_PATH}
     - ~/${COMPOSER_HOME}:$HOME/${COMPOSER_HOME}
     - ~/${COMPOSER_CACHE_DIR}:$HOME/${COMPOSER_CACHE_DIR}
     - ./bitrix/config/${DEV_1}/.settings.php:${REMOTE_SITES_PATH}/${DEV_1}/bitrix/
     - ./bitrix/config/${DEV_1}/dbconn.php:${REMOTE_SITES_PATH}/${DEV_1}/bitrix/php_interface/
     - ./bitrix/config/${DEV_1}/configurations:${REMOTE_SITES_PATH}/${DEV_1}/local/php_interface/configurations
    working_dir: ${REMOTE_SITES_PATH}
    command: "php-fpm"
  db:
    image: mariadb
    restart: always
    ports:
     - "${DB_LOCAL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  adminer:
    image: adminer
    ports:
     - "${ADMINER_LOCAL_PORT}:8080"
  redis:
    image: redis
    restart: always
    ports:
     - "${REDIS_LOCAL_PORT}:6379"